import operator
from typing import Annotated

from pydantic import BaseModel, Field
from typing_extensions import Literal


SynthesisStatus = Literal[
    "",
    "complete",
    "insufficient_data",
    # runtime-only (not emitted by the structured LLM schema)
    "no_evidence",
    "invalid_structured_output",
]


class GraphState(BaseModel):
    """
    Industry standard Pydantic state for the Market Intelligence Graph.
    Using Annotated with operator.add allows for seamless context accumulation.
    """

    query: str = Field(..., description="The original user natural language query.")

    entities: list[str] = Field(
        default_factory=list,
        description="List of entities extracted by the LLM (Companies, Products, Sectors).",
    )

    intent: str = Field(
        default="",
        description="Router intent: RESEARCH, COMPETITION, or IRRELEVANT.",
    )

    context: list[str] = Field(
        default_factory=list,
        description="Retrieved graph + vector context (replaced each retrieve).",
    )

    response: str = Field(
        default="",
        description="The final synthesized answer generated by the LLM.",
    )

    critique: str = Field(
        default="",
        description="Feedback from the Red Team critique node; 'PASS' when report is approved.",
    )

    revision_count: Annotated[int, operator.add] = Field(
        default=0,
        description="Safety counter to prevent infinite refinement loops (max 3). Accumulates via operator.add.",
    )

    retrieved_ids: list[str] = Field(
        default_factory=list,
        description="Chunk IDs from vector search (for structured debugging).",
    )

    retrieved_metadata: list[dict] = Field(
        default_factory=list,
        description="Entity metadata from vector results: [{entity, type}, ...] for grounding.",
    )

    critique_score: float = Field(
        default=0.0,
        description="Auditor score 0.0-1.0; threshold 0.85 for pass.",
    )

    eval_score: float = Field(
        default=0.0,
        description="Ragas faithfulness score 0.0-1.0; threshold 0.8 for pass.",
    )

    ragas_scores: dict | None = Field(
        default=None,
        description="Full RagasMetrics breakdown for LangSmith traces (faithfulness, answer_relevancy, context_precision, critique_instruction, is_passing).",
    )

    critique_instruction: str = Field(
        default="",
        description="Evaluator instructions for the Critique node when scores are below threshold.",
    )

    is_refused: bool = Field(
        default=False,
        description="True when fallback (evidence-only) used; for refusal-rate tracking.",
    )

    context_sufficient: bool = Field(
        default=True,
        description="Grader (pre-synthesis): True if retrieved context is sufficient to answer query.",
    )

    retrieval_revision_count: Annotated[int, operator.add] = Field(
        default=0,
        description="Agentic loop: increments on each rewrite->retrieve cycle; max 2.",
    )

    mmr_lambda: float = Field(
        default=1.0,
        description="MMR diversity weight [0,1] after HITL resume; 1.0 = relevance-only default.",
    )

    pending_mmr_refetch: bool = Field(
        default=False,
        description="After HITL resume: route to retrieve again with mmr_lambda for MMR re-ranking.",
    )

    mmr_hitl_done: bool = Field(
        default=False,
        description="True after human set λ once; prevents repeated interrupts on same run.",
    )

    history: list[dict] = Field(
        default_factory=list,
        description="Conversation history for coreference: [{query, response}, ...]. Used by extractor.",
    )

    exit_reason: str = Field(
        default="",
        description=(
            "Terminal reason: out_of_scope, max_retries_exceeded, requires_human_review, "
            "or empty when normal."
        ),
    )

    partial_answer: bool = Field(
        default=False,
        description="True when synthesis should produce best-effort output after grader max retries.",
    )

    synthesis_status: SynthesisStatus = Field(
        default="",
        description=(
            "Synthesis verdict (strict): "
            '"complete" | "insufficient_data" (from LLM structured output), '
            '"no_evidence" (runtime: no indexed evidence after retrieval limits), '
            '"invalid_structured_output" (runtime: schema/status invalid after retry), '
            'or "" when unset.'
        ),
    )
    synthesis_confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Model-reported confidence 0-1 from structured synthesis output.",
    )
    synthesis_requires_critique: bool = Field(
        default=False,
        description="Structured flag: route to critique for self-correction when true.",
    )

    requires_human_review: bool = Field(
        default=False,
        description="Deterministic escalation: route to human_review node when true.",
    )
    escalation_reason: str = Field(
        default="",
        description="Machine-readable escalation code (e.g. user_requested_human, policy_gap_insufficient_grounding).",
    )

    last_error: dict | None = Field(
        default=None,
        description=(
            "Serialized ToolError from infrastructure/operation failures (not no-evidence outcomes). "
            "See app.errors.models.ToolError."
        ),
    )

    retrieval_errors: list[dict] = Field(
        default_factory=list,
        description="Per-backend ToolError dicts from retrieve (graph/vector) when a datastore call failed.",
    )

    class Config:
        """Allows arbitrary types if you decide to add DB drivers directly to state."""

        arbitrary_types_allowed = True
