import operator
from typing import Annotated

from pydantic import BaseModel, Field


class GraphState(BaseModel):
    """
    Industry standard Pydantic state for the Market Intelligence Graph.
    Using Annotated with operator.add allows for seamless context accumulation.
    """

    query: str = Field(..., description="The original user natural language query.")

    entities: list[str] = Field(
        default_factory=list,
        description="List of entities extracted by the LLM (Companies, Products, Sectors).",
    )

    intent: str = Field(
        default="",
        description="Router intent: RESEARCH, COMPETITION, or IRRELEVANT.",
    )

    context: Annotated[list[str], operator.add] = Field(
        default_factory=list,
        description="Accumulated data from Vector and Graph lookups.",
    )

    response: str = Field(
        default="",
        description="The final synthesized answer generated by the LLM.",
    )

    critique: str = Field(
        default="",
        description="Feedback from the Red Team critique node; 'PASS' when report is approved.",
    )

    revision_count: Annotated[int, operator.add] = Field(
        default=0,
        description="Safety counter to prevent infinite refinement loops (max 3). Accumulates via operator.add.",
    )

    retrieved_ids: list[str] = Field(
        default_factory=list,
        description="Chunk IDs from vector search (for structured debugging).",
    )

    retrieved_metadata: list[dict] = Field(
        default_factory=list,
        description="Entity metadata from vector results: [{entity, type}, ...] for grounding.",
    )

    critique_score: float = Field(
        default=0.0,
        description="Auditor score 0.0-1.0; threshold 0.85 for pass.",
    )

    eval_score: float = Field(
        default=0.0,
        description="Ragas faithfulness score 0.0-1.0; threshold 0.8 for pass.",
    )

    ragas_scores: dict | None = Field(
        default=None,
        description="Full RagasMetrics breakdown for LangSmith traces (faithfulness, answer_relevancy, context_precision, critique_instruction, is_passing).",
    )

    critique_instruction: str = Field(
        default="",
        description="Evaluator instructions for the Critique node when scores are below threshold.",
    )

    is_refused: bool = Field(
        default=False,
        description="True when fallback (evidence-only) used; for refusal-rate tracking.",
    )

    context_sufficient: bool = Field(
        default=True,
        description="Grader (pre-synthesis): True if retrieved context is sufficient to answer query.",
    )

    retrieval_revision_count: Annotated[int, operator.add] = Field(
        default=0,
        description="Agentic loop: increments on each rewrite->retrieve cycle; max 2.",
    )

    history: list[dict] = Field(
        default_factory=list,
        description="Conversation history for coreference: [{query, response}, ...]. Used by extractor.",
    )

    class Config:
        """Allows arbitrary types if you decide to add DB drivers directly to state."""

        arbitrary_types_allowed = True
